#!/usr/bin/env bash
# install-user.sh — copy tokopt-vscode agents + skills into ~/.copilot/
#
# Usage: install-user.sh [--dry-run]
#
# Copies:
#   .github/agents/*.agent.md → ~/.copilot/agents/
#   .github/skills/*/SKILL.md → ~/.copilot/skills/
#
# Prompts are NOT installed at user scope (VS Code reads .prompt.md
# only from workspace .github/prompts/). For slash-command UX, use
# install-workspace.sh instead.
#
# Tracks installed files in ~/.copilot/.tokopt-vscode-manifest so
# uninstall.sh can remove only what this installer placed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
elif [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  cat <<EOF
Usage: $(basename "$0") [--dry-run]

Copies tokopt-vscode user-scope assets into ~/.copilot/.
Prompts (.prompt.md) are NOT installed at user scope — use install-workspace.sh
for those.

Options:
  --dry-run   Print what would be copied without writing
EOF
  exit 1
fi

USER_COPILOT="$HOME/.copilot"
MANIFEST="$USER_COPILOT/.tokopt-vscode-manifest"

mkdir -p "$USER_COPILOT/agents" "$USER_COPILOT/skills"

run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "DRY: $*"
  else
    echo "+ $*"
    "$@"
  fi
}

declare -a INSTALLED=()

# Agents — flat directory of .agent.md files
for src in "$SRC_ROOT"/.github/agents/*.agent.md; do
  [ -f "$src" ] || continue
  base=$(basename "$src")
  dst="$USER_COPILOT/agents/$base"
  if [ -e "$dst" ] && ! grep -q "$dst" "$MANIFEST" 2>/dev/null; then
    echo "WARN: '$dst' exists and is not in the tokopt-vscode manifest." >&2
    echo "      Overwriting — original will be lost." >&2
  fi
  run cp "$src" "$dst"
  INSTALLED+=("$dst")
done

# Skills — each skill is a dir with SKILL.md (+ optional resources)
for src_dir in "$SRC_ROOT"/.github/skills/*/; do
  [ -d "$src_dir" ] || continue
  skill_name=$(basename "$src_dir")
  dst_dir="$USER_COPILOT/skills/$skill_name"
  run mkdir -p "$dst_dir"
  for f in "$src_dir"*; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    [ "$base" = ".gitkeep" ] && continue
    run cp "$f" "$dst_dir/$base"
    INSTALLED+=("$dst_dir/$base")
  done
done

# Update manifest (only write on real run)
if [ "$DRY_RUN" -eq 0 ]; then
  {
    echo "# tokopt-vscode manifest — generated by install-user.sh"
    echo "# Each line is an absolute path to a file installed by this script."
    echo "# Used by uninstall.sh for surgical removal. Do not edit manually."
    echo "# Last update: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    for f in "${INSTALLED[@]}"; do
      echo "$f"
    done
  } > "$MANIFEST"
  echo
  echo "Install complete (${#INSTALLED[@]} files). Manifest written to:"
  echo "  $MANIFEST"
  echo
  echo "Open VS Code Insiders in any workspace and verify:"
  echo "  - Copilot Chat picker (@) shows @token-doctor, @prompt-optimizer"
  echo "  - Natural-language requests like 'audit my repo for tokens' load"
  echo "    the token-audit skill"
  echo
  echo "Slash commands (/) are workspace-scoped only — use install-workspace.sh"
  echo "in repos where you want them."
else
  echo
  echo "[dry-run] No files modified. Would install ${#INSTALLED[@]} files."
fi

# --- tokopt CLI detection (post-install) ------------------------------------
# The installed agents + skills are thin wrappers around the `tokopt` Go CLI.
# Without the binary on PATH, every prompt and agent will fail at runtime
# with "tokopt: command not found". Surface this NOW, not later in Chat.

echo
if command -v tokopt >/dev/null 2>&1; then
  echo "✓ tokopt CLI detected: $(command -v tokopt) ($(tokopt --version 2>/dev/null || echo 'version unknown'))"
elif [ -x "$HOME/go/bin/tokopt" ]; then
  echo "⚠ tokopt CLI found at $HOME/go/bin/tokopt but NOT on PATH."
  echo "  Add this to your shell rc to fix:"
  echo "      export PATH=\"\$HOME/go/bin:\$PATH\""
else
  cat <<'HINT'
⚠ tokopt CLI not detected. The installed agents + skills require it.

Install in one line (recommended — pre-built binary):

    curl -fsSL https://raw.githubusercontent.com/shinyay/tokopt/main/scripts/install.sh | sh

Or build from source (requires Go ≥ 1.24):

    go install github.com/shinyay/getting-started-with-token-optimization/tools/tokopt/cmd/tokopt@latest

After install, verify with: tokopt --version
HINT
fi
